{"uid":"1da166f80b365419","name":"test_change_country_not_found_or_forbidden[authorize_client-99999999-403]","fullName":"tests.orders.test_group_order_change_country#test_change_country_not_found_or_forbidden","historyId":"f8f3bc375b16b0db87438afce93840f2","time":{"start":1744589644942,"stop":1744589645401,"duration":459},"description":"Негативные тесты: изменение несуществующего заказа или без прав","descriptionHtml":"<p>Негативные тесты: изменение несуществующего заказа или без прав</p>\n","status":"skipped","statusMessage":"XFAIL https://ru.yougile.com/team/01c2a92f1328/#IT-507\n\nAssertionError: Ожидался статус 403, но получен 405","statusTrace":"api_client = <api_tests.utils.api_client.APIClient object at 0x7f5d06171b10>\nauthorize_func = <function authorize_client at 0x7f5d06616340>\nint_id = 99999999, expected_status = 403\n\n    @pytest.mark.xfail(reason = \"https://ru.yougile.com/team/01c2a92f1328/#IT-507\")\n    @pytest.mark.parametrize(\n        \"authorize_func, int_id, expected_status\",\n        [\n            (authorize_client, 99999999, 403),  # Заказ не найден\n            (authorize_partner, 100, 403),  # Нет прав на изменение\n        ],\n    )\n    def test_change_country_not_found_or_forbidden(api_client, authorize_func, int_id, expected_status):\n        \"\"\"Негативные тесты: изменение несуществующего заказа или без прав\"\"\"\n        authorize_func(api_client)\n        payload = {\"int_id\": int_id, \"country_id\": 2}\n        response = api_client.post(\"/orders/group_order/change_country\", json=payload)\n>       assert_response_status_and_error(response, expected_status)\n\napi_tests/tests/orders/test_group_order_change_country.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = {'error': '', 'status_code': 405}, expected_status = 403\n\n    def assert_response_status_and_error(response, expected_status):\n        actual_status = response[\"status_code\"]\n>       assert actual_status == expected_status, f\"Ожидался статус {expected_status}, но получен {actual_status}\"\nE       AssertionError: Ожидался статус 403, но получен 405\n\napi_tests/utils/asserts.py:39: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"api_client","time":{"start":1744589638916,"stop":1744589638916,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"api_client::0","time":{"start":1744589646818,"stop":1744589646819,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='https://ru.yougile.com/team/01c2a92f1328/#IT-507')"},{"name":"parentSuite","value":"tests.orders"},{"name":"suite","value":"test_group_order_change_country"},{"name":"host","value":"fv-az1477-977"},{"name":"thread","value":"1852-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.orders.test_group_order_change_country"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"authorize_func","value":"<function authorize_client at 0x7f5d06616340>"},{"name":"expected_status","value":"403"},{"name":"int_id","value":"99999999"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='https://ru.yougile.com/team/01c2a92f1328/#IT-507')"]},"source":"1da166f80b365419.json","parameterValues":["<function authorize_client at 0x7f5d06616340>","403","99999999"]}